title: Control_Panel Installation Instructions
description: A Control Line Timer Remote Interface
#remote_theme: just-the-docs/just-the-docs
theme: "just-the-docs"
color_scheme: custom

logo: "/assets/images/CircuitFlyer.png"

url: https://circuitflyer.com/

aux_links:
  Control_Panel on Github: https://github.com/circuitflyer/Control_Panel

callouts:
  highlight:
      color: yellow
  warning:
    title: Warning
    color: red

heading_anchors: true
